---
cluster:
  consensus:
    compact_wal_entries: 128
    tick_period_ms: 100
  enabled: false
  p2p:
    enable_tls: false
    port: 6335
log_level: INFO
service:
  enable_cors: true
  enable_tls: false
  grpc_port: 6334
  host: 0.0.0.0
  http_port: 6333
  max_request_size_mb: 32
  max_workers: 0
  verify_https_client_certificate: false
storage:
  collection:
    quantization: null
    replication_factor: 1
    strict_mode:
      enabled: false
      max_query_limit: null
      max_timeout: null
      search_allow_exact: null
      search_max_hnsw_ef: null
      search_max_oversampling: null
      unindexed_filtering_retrieve: null
      unindexed_filtering_update: null
    vectors:
      on_disk: null
    write_consistency_factor: 1
  hnsw_index:
    ef_construct: 100
    full_scan_threshold_kb: 10000
    m: 16
    max_indexing_threads: 0
    on_disk: false
    payload_m: null
  node_type: Normal
  on_disk_payload: true
  optimizers:
    default_segment_number: 2
    deleted_threshold: 0.2
    flush_interval_sec: 5
    indexing_threshold_kb: 20000
    max_optimization_threads: null
    max_segment_size_kb: null
    memmap_threshold_kb: null
    vacuum_min_vector_number: 1000
  performance:
    max_optimization_threads: 0
    max_search_threads: 0
    optimizer_cpu_budget: 0
    update_rate_limit: null
  shard_transfer_method: null
  snapshots_config:
    snapshots_storage: local
  snapshots_path: ./snapshots
  storage_path: ./storage
  temp_path: null
  update_concurrency: null
  wal:
    wal_capacity_mb: 32
    wal_segments_ahead: 0
telemetry_disabled: false
tls:
  ca_cert: ./tls/cacert.pem
  cert: ./tls/cert.pem
  cert_ttl: 3600
  key: ./tls/key.pem
