services:
  qdrant:
    image: qdrant/qdrant:v1.13.5-unprivileged
    container_name: knowledgeplatform-qdrant
    restart: unless-stopped
    user: "0:0"
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - knowledgeplatform
      - default

  typedb:
    image: vaticle/typedb:2.29.1
    container_name: knowledgeplatform-typedb
    ports:
      - "1729:1729"
    restart: unless-stopped
    user: "0:0"
    volumes:
      # Mount to both directories to give cross architecture compatibility.
      # There can't be any race conditions as only one of the mounting locations will be used. 
      - ./data/typedb:/opt/typedb-all-linux-x86_64/server/data
      - ./data/typedb:/opt/typedb-all-linux-arm64/server/data
    healthcheck:
      test:
        - CMD-SHELL
        # The else part should never be reached but exists as a failsafe error message that is more informative.
        - |
          if [ -f /opt/typedb-all-linux-x86_64/typedb ]; then
            CMD=/opt/typedb-all-linux-x86_64/typedb
          elif [ -f /opt/typedb-all-linux-arm64/typedb ]; then
            CMD=/opt/typedb-all-linux-arm64/typedb
          else
            echo "ERROR: Could not find typedb executable for any architecture." >&2
            exit 1
          fi
          $$CMD console --core=localhost:1729 --command='database list' > /dev/null 2>&1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - knowledgeplatform
      - default

networks:
  knowledgeplatform:
    driver: bridge